# Generated by Django 2.2.1 on 2019-07-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190717_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_upvoted',
            field=models.TextField(default=''),
        ),
    ]
