# Generated by Django 2.2.1 on 2019-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190717_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='domain',
            field=models.CharField(choices=[('IF', 'Infrastructure'), ('RD', 'Roads'), ('PT', 'Plant Trees'), ('AP', 'Animal Problems'), ('OTH', 'Others')], default='OTH', max_length=5),
        ),
    ]
